package praca;

public enum Zadania {

    DOSTARCZENIE_PACZEK,
    KONTAKT_Z_KLIENTEM,
    SORTOWANIE_PACZEK,
    ŁADOWANIE_SAMOCHODU,
    ROZWIĄZYWANIE_KONFLIKTÓW,
    PRZYJMOWANIE_PRACOWNIKÓW,
    ODBIERANIE_PACZEK
}
